version: '3.8'
services:
    

  postgres:
    restart: always
    image: postgres:14
    container_name: postgresql14
    volumes:
      - ../postgresql-data:/var/lib/postgresql/data
      - ./postgresql-init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgresql/data/14
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  django:
    restart: always
    image: django-dev
    container_name: django-dev
    command:  >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    build:
      context: .
    volumes:
      - .:/webapp/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  celery:
    build: .
    container_name: 'celery'
    command: celery -A library worker -B
    volumes:
      - .:/webapp/
    links:
      - redis
    depends_on:
      - django
      - redis

  redis:
    restart: always
    container_name: 'redis-server'
    image: redis
    ports:
    - "6379:6379"
